//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from database.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Data;
using ObjectSql;
using ObjectSql.QueryInterfaces;

namespace ObjectSql.Test.Database.TestDatabase
{
	namespace dbo
	{
		[Table("Alphabetical list of products",Schema="dbo")]
		public partial class Alphabetical_list_of_products
		{
			[Column("ProductID",TypeName="int")] public int ProductID {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("SupplierID",TypeName="int")] public int? SupplierID {get; set;}
			[Column("CategoryID",TypeName="int")] public int? CategoryID {get; set;}
			[Column("QuantityPerUnit",TypeName="nvarchar")] public string QuantityPerUnit {get; set;}
			[Column("UnitPrice",TypeName="money")] public decimal? UnitPrice {get; set;}
			[Column("UnitsInStock",TypeName="smallint")] public short? UnitsInStock {get; set;}
			[Column("UnitsOnOrder",TypeName="smallint")] public short? UnitsOnOrder {get; set;}
			[Column("ReorderLevel",TypeName="smallint")] public short? ReorderLevel {get; set;}
			[Column("Discontinued",TypeName="bit")] public bool Discontinued {get; set;}
			[Column("CategoryName",TypeName="nvarchar")] public string CategoryName {get; set;}
		}

		[Table("Categories",Schema="dbo")]
		public partial class Categories
		{
			[Column("CategoryID",TypeName="int")] public int CategoryID {get; set;}
			[Column("CategoryName",TypeName="nvarchar")] public string CategoryName {get; set;}
			[Column("Description",TypeName="ntext")] public string Description {get; set;}
			[Column("Picture",TypeName="image")] public byte[] Picture {get; set;}
		}

		[Table("Category Sales for 1997",Schema="dbo")]
		public partial class Category_Sales_for_1997
		{
			[Column("CategoryName",TypeName="nvarchar")] public string CategoryName {get; set;}
			[Column("CategorySales",TypeName="money")] public decimal? CategorySales {get; set;}
		}

		[Table("Current Product List",Schema="dbo")]
		public partial class Current_Product_List
		{
			[Column("ProductID",TypeName="int")] public int ProductID {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
		}

		[Table("Customer and Suppliers by City",Schema="dbo")]
		public partial class Customer_and_Suppliers_by_City
		{
			[Column("City",TypeName="nvarchar")] public string City {get; set;}
			[Column("CompanyName",TypeName="nvarchar")] public string CompanyName {get; set;}
			[Column("ContactName",TypeName="nvarchar")] public string ContactName {get; set;}
			[Column("Relationship",TypeName="varchar")] public string Relationship {get; set;}
		}

		[Table("CustomerCustomerDemo",Schema="dbo")]
		public partial class CustomerCustomerDemo
		{
			[Column("CustomerID",TypeName="nchar")] public string CustomerID {get; set;}
			[Column("CustomerTypeID",TypeName="nchar")] public string CustomerTypeID {get; set;}
		}

		[Table("CustomerDemographics",Schema="dbo")]
		public partial class CustomerDemographics
		{
			[Column("CustomerTypeID",TypeName="nchar")] public string CustomerTypeID {get; set;}
			[Column("CustomerDesc",TypeName="ntext")] public string CustomerDesc {get; set;}
		}

		[Table("Customers",Schema="dbo")]
		public partial class Customers
		{
			[Column("CustomerID",TypeName="nchar")] public string CustomerID {get; set;}
			[Column("CompanyName",TypeName="nvarchar")] public string CompanyName {get; set;}
			[Column("ContactName",TypeName="nvarchar")] public string ContactName {get; set;}
			[Column("ContactTitle",TypeName="nvarchar")] public string ContactTitle {get; set;}
			[Column("Address",TypeName="nvarchar")] public string Address {get; set;}
			[Column("City",TypeName="nvarchar")] public string City {get; set;}
			[Column("Region",TypeName="nvarchar")] public string Region {get; set;}
			[Column("PostalCode",TypeName="nvarchar")] public string PostalCode {get; set;}
			[Column("Country",TypeName="nvarchar")] public string Country {get; set;}
			[Column("Phone",TypeName="nvarchar")] public string Phone {get; set;}
			[Column("Fax",TypeName="nvarchar")] public string Fax {get; set;}
		}

		[Table("Employees",Schema="dbo")]
		public partial class Employees
		{
			[Column("EmployeeID",TypeName="int")] public int EmployeeID {get; set;}
			[Column("LastName",TypeName="nvarchar")] public string LastName {get; set;}
			[Column("FirstName",TypeName="nvarchar")] public string FirstName {get; set;}
			[Column("Title",TypeName="nvarchar")] public string Title {get; set;}
			[Column("TitleOfCourtesy",TypeName="nvarchar")] public string TitleOfCourtesy {get; set;}
			[Column("BirthDate",TypeName="datetime")] public DateTime? BirthDate {get; set;}
			[Column("HireDate",TypeName="datetime")] public DateTime? HireDate {get; set;}
			[Column("Address",TypeName="nvarchar")] public string Address {get; set;}
			[Column("City",TypeName="nvarchar")] public string City {get; set;}
			[Column("Region",TypeName="nvarchar")] public string Region {get; set;}
			[Column("PostalCode",TypeName="nvarchar")] public string PostalCode {get; set;}
			[Column("Country",TypeName="nvarchar")] public string Country {get; set;}
			[Column("HomePhone",TypeName="nvarchar")] public string HomePhone {get; set;}
			[Column("Extension",TypeName="nvarchar")] public string Extension {get; set;}
			[Column("Photo",TypeName="image")] public byte[] Photo {get; set;}
			[Column("Notes",TypeName="ntext")] public string Notes {get; set;}
			[Column("ReportsTo",TypeName="int")] public int? ReportsTo {get; set;}
			[Column("PhotoPath",TypeName="nvarchar")] public string PhotoPath {get; set;}
		}

		[Table("EmployeeTerritories",Schema="dbo")]
		public partial class EmployeeTerritories
		{
			[Column("EmployeeID",TypeName="int")] public int EmployeeID {get; set;}
			[Column("TerritoryID",TypeName="nvarchar")] public string TerritoryID {get; set;}
		}

		[Table("Invoices",Schema="dbo")]
		public partial class Invoices
		{
			[Column("ShipName",TypeName="nvarchar")] public string ShipName {get; set;}
			[Column("ShipAddress",TypeName="nvarchar")] public string ShipAddress {get; set;}
			[Column("ShipCity",TypeName="nvarchar")] public string ShipCity {get; set;}
			[Column("ShipRegion",TypeName="nvarchar")] public string ShipRegion {get; set;}
			[Column("ShipPostalCode",TypeName="nvarchar")] public string ShipPostalCode {get; set;}
			[Column("ShipCountry",TypeName="nvarchar")] public string ShipCountry {get; set;}
			[Column("CustomerID",TypeName="nchar")] public string CustomerID {get; set;}
			[Column("CustomerName",TypeName="nvarchar")] public string CustomerName {get; set;}
			[Column("Address",TypeName="nvarchar")] public string Address {get; set;}
			[Column("City",TypeName="nvarchar")] public string City {get; set;}
			[Column("Region",TypeName="nvarchar")] public string Region {get; set;}
			[Column("PostalCode",TypeName="nvarchar")] public string PostalCode {get; set;}
			[Column("Country",TypeName="nvarchar")] public string Country {get; set;}
			[Column("Salesperson",TypeName="nvarchar")] public string Salesperson {get; set;}
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("OrderDate",TypeName="datetime")] public DateTime? OrderDate {get; set;}
			[Column("RequiredDate",TypeName="datetime")] public DateTime? RequiredDate {get; set;}
			[Column("ShippedDate",TypeName="datetime")] public DateTime? ShippedDate {get; set;}
			[Column("ShipperName",TypeName="nvarchar")] public string ShipperName {get; set;}
			[Column("ProductID",TypeName="int")] public int ProductID {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("UnitPrice",TypeName="money")] public decimal UnitPrice {get; set;}
			[Column("Quantity",TypeName="smallint")] public short Quantity {get; set;}
			[Column("Discount",TypeName="real")] public float Discount {get; set;}
			[Column("ExtendedPrice",TypeName="money")] public decimal? ExtendedPrice {get; set;}
			[Column("Freight",TypeName="money")] public decimal? Freight {get; set;}
		}

		[Table("MultiTypeTable",Schema="dbo")]
		public partial class MultiTypeTable
		{
			[Column("Id",TypeName="int")] public int Id {get; set;}
			[Column("BigInt",TypeName="bigint")] public long? BigInt {get; set;}
			[Column("Bit",TypeName="bit")] public bool? Bit {get; set;}
			[Column("Binary",TypeName="binary")] public byte[] Binary {get; set;}
			[Column("Char",TypeName="char")] public string Char {get; set;}
			[Column("Date",TypeName="date")] public DateTime? Date {get; set;}
			[Column("DateTime",TypeName="datetime")] public DateTime? DateTime {get; set;}
			[Column("DateTime2",TypeName="datetime2")] public DateTime? DateTime2 {get; set;}
			[Column("DateTimeOffcet",TypeName="datetimeoffset")] public DateTimeOffset? DateTimeOffcet {get; set;}
			[Column("Decimal",TypeName="decimal")] public decimal? Decimal {get; set;}
			[Column("Float",TypeName="float")] public double? Float {get; set;}
			[Column("Image",TypeName="image")] public byte[] Image {get; set;}
			[Column("Int",TypeName="int")] public int? Int {get; set;}
			[Column("Money",TypeName="money")] public decimal? Money {get; set;}
			[Column("NChar",TypeName="nchar")] public string NChar {get; set;}
			[Column("NText",TypeName="ntext")] public string NText {get; set;}
			[Column("Numeric",TypeName="numeric")] public decimal? Numeric {get; set;}
			[Column("NVarchar",TypeName="nvarchar")] public string NVarchar {get; set;}
			[Column("Real",TypeName="real")] public float? Real {get; set;}
			[Column("SmallDateTime",TypeName="smalldatetime")] public DateTime? SmallDateTime {get; set;}
			[Column("SmallInt",TypeName="smallint")] public short? SmallInt {get; set;}
			[Column("SmallMoney",TypeName="smallmoney")] public decimal? SmallMoney {get; set;}
			[Column("Text",TypeName="text")] public string Text {get; set;}
			[Column("TinyInt",TypeName="tinyint")] public byte? TinyInt {get; set;}
			[Column("Guid",TypeName="uniqueidentifier")] public Guid? Guid {get; set;}
			[Column("Varbinary",TypeName="varbinary")] public byte[] Varbinary {get; set;}
			[Column("Varchar",TypeName="varchar")] public string Varchar {get; set;}
			[Column("Xml",TypeName="xml")] public string Xml {get; set;}
		}

		[Table("Order Details",Schema="dbo")]
		public partial class Order_Details
		{
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("ProductID",TypeName="int")] public int ProductID {get; set;}
			[Column("UnitPrice",TypeName="money")] public decimal UnitPrice {get; set;}
			[Column("Quantity",TypeName="smallint")] public short Quantity {get; set;}
			[Column("Discount",TypeName="real")] public float Discount {get; set;}
		}

		[Table("Order Details Extended",Schema="dbo")]
		public partial class Order_Details_Extended
		{
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("ProductID",TypeName="int")] public int ProductID {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("UnitPrice",TypeName="money")] public decimal UnitPrice {get; set;}
			[Column("Quantity",TypeName="smallint")] public short Quantity {get; set;}
			[Column("Discount",TypeName="real")] public float Discount {get; set;}
			[Column("ExtendedPrice",TypeName="money")] public decimal? ExtendedPrice {get; set;}
		}

		[Table("Order Subtotals",Schema="dbo")]
		public partial class Order_Subtotals
		{
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("Subtotal",TypeName="money")] public decimal? Subtotal {get; set;}
		}

		[Table("Orders",Schema="dbo")]
		public partial class Orders
		{
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("CustomerID",TypeName="nchar")] public string CustomerID {get; set;}
			[Column("EmployeeID",TypeName="int")] public int? EmployeeID {get; set;}
			[Column("OrderDate",TypeName="datetime")] public DateTime? OrderDate {get; set;}
			[Column("RequiredDate",TypeName="datetime")] public DateTime? RequiredDate {get; set;}
			[Column("ShippedDate",TypeName="datetime")] public DateTime? ShippedDate {get; set;}
			[Column("ShipVia",TypeName="int")] public int? ShipVia {get; set;}
			[Column("Freight",TypeName="money")] public decimal? Freight {get; set;}
			[Column("ShipName",TypeName="nvarchar")] public string ShipName {get; set;}
			[Column("ShipAddress",TypeName="nvarchar")] public string ShipAddress {get; set;}
			[Column("ShipCity",TypeName="nvarchar")] public string ShipCity {get; set;}
			[Column("ShipRegion",TypeName="nvarchar")] public string ShipRegion {get; set;}
			[Column("ShipPostalCode",TypeName="nvarchar")] public string ShipPostalCode {get; set;}
			[Column("ShipCountry",TypeName="nvarchar")] public string ShipCountry {get; set;}
		}

		[Table("Orders Qry",Schema="dbo")]
		public partial class Orders_Qry
		{
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("CustomerID",TypeName="nchar")] public string CustomerID {get; set;}
			[Column("EmployeeID",TypeName="int")] public int? EmployeeID {get; set;}
			[Column("OrderDate",TypeName="datetime")] public DateTime? OrderDate {get; set;}
			[Column("RequiredDate",TypeName="datetime")] public DateTime? RequiredDate {get; set;}
			[Column("ShippedDate",TypeName="datetime")] public DateTime? ShippedDate {get; set;}
			[Column("ShipVia",TypeName="int")] public int? ShipVia {get; set;}
			[Column("Freight",TypeName="money")] public decimal? Freight {get; set;}
			[Column("ShipName",TypeName="nvarchar")] public string ShipName {get; set;}
			[Column("ShipAddress",TypeName="nvarchar")] public string ShipAddress {get; set;}
			[Column("ShipCity",TypeName="nvarchar")] public string ShipCity {get; set;}
			[Column("ShipRegion",TypeName="nvarchar")] public string ShipRegion {get; set;}
			[Column("ShipPostalCode",TypeName="nvarchar")] public string ShipPostalCode {get; set;}
			[Column("ShipCountry",TypeName="nvarchar")] public string ShipCountry {get; set;}
			[Column("CompanyName",TypeName="nvarchar")] public string CompanyName {get; set;}
			[Column("Address",TypeName="nvarchar")] public string Address {get; set;}
			[Column("City",TypeName="nvarchar")] public string City {get; set;}
			[Column("Region",TypeName="nvarchar")] public string Region {get; set;}
			[Column("PostalCode",TypeName="nvarchar")] public string PostalCode {get; set;}
			[Column("Country",TypeName="nvarchar")] public string Country {get; set;}
		}

		[Table("Product Sales for 1997",Schema="dbo")]
		public partial class Product_Sales_for_1997
		{
			[Column("CategoryName",TypeName="nvarchar")] public string CategoryName {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("ProductSales",TypeName="money")] public decimal? ProductSales {get; set;}
		}

		[Table("Products",Schema="dbo")]
		public partial class Products
		{
			[Column("ProductID",TypeName="int")] public int ProductID {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("SupplierID",TypeName="int")] public int? SupplierID {get; set;}
			[Column("CategoryID",TypeName="int")] public int? CategoryID {get; set;}
			[Column("QuantityPerUnit",TypeName="nvarchar")] public string QuantityPerUnit {get; set;}
			[Column("UnitPrice",TypeName="money")] public decimal? UnitPrice {get; set;}
			[Column("UnitsInStock",TypeName="smallint")] public short? UnitsInStock {get; set;}
			[Column("UnitsOnOrder",TypeName="smallint")] public short? UnitsOnOrder {get; set;}
			[Column("ReorderLevel",TypeName="smallint")] public short? ReorderLevel {get; set;}
			[Column("Discontinued",TypeName="bit")] public bool Discontinued {get; set;}
		}

		[Table("Products Above Average Price",Schema="dbo")]
		public partial class Products_Above_Average_Price
		{
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("UnitPrice",TypeName="money")] public decimal? UnitPrice {get; set;}
		}

		[Table("Products by Category",Schema="dbo")]
		public partial class Products_by_Category
		{
			[Column("CategoryName",TypeName="nvarchar")] public string CategoryName {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("QuantityPerUnit",TypeName="nvarchar")] public string QuantityPerUnit {get; set;}
			[Column("UnitsInStock",TypeName="smallint")] public short? UnitsInStock {get; set;}
			[Column("Discontinued",TypeName="bit")] public bool Discontinued {get; set;}
		}

		[Table("Quarterly Orders",Schema="dbo")]
		public partial class Quarterly_Orders
		{
			[Column("CustomerID",TypeName="nchar")] public string CustomerID {get; set;}
			[Column("CompanyName",TypeName="nvarchar")] public string CompanyName {get; set;}
			[Column("City",TypeName="nvarchar")] public string City {get; set;}
			[Column("Country",TypeName="nvarchar")] public string Country {get; set;}
		}

		[Table("Region",Schema="dbo")]
		public partial class Region
		{
			[Column("RegionID",TypeName="int")] public int RegionID {get; set;}
			[Column("RegionDescription",TypeName="nchar")] public string RegionDescription {get; set;}
		}

		[Table("Sales by Category",Schema="dbo")]
		public partial class Sales_by_Category
		{
			[Column("CategoryID",TypeName="int")] public int CategoryID {get; set;}
			[Column("CategoryName",TypeName="nvarchar")] public string CategoryName {get; set;}
			[Column("ProductName",TypeName="nvarchar")] public string ProductName {get; set;}
			[Column("ProductSales",TypeName="money")] public decimal? ProductSales {get; set;}
		}

		[Table("Sales Totals by Amount",Schema="dbo")]
		public partial class Sales_Totals_by_Amount
		{
			[Column("SaleAmount",TypeName="money")] public decimal? SaleAmount {get; set;}
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("CompanyName",TypeName="nvarchar")] public string CompanyName {get; set;}
			[Column("ShippedDate",TypeName="datetime")] public DateTime? ShippedDate {get; set;}
		}

		[Table("Shippers",Schema="dbo")]
		public partial class Shippers
		{
			[Column("ShipperID",TypeName="int")] public int ShipperID {get; set;}
			[Column("CompanyName",TypeName="nvarchar")] public string CompanyName {get; set;}
			[Column("Phone",TypeName="nvarchar")] public string Phone {get; set;}
		}

		[Table("Summary of Sales by Quarter",Schema="dbo")]
		public partial class Summary_of_Sales_by_Quarter
		{
			[Column("ShippedDate",TypeName="datetime")] public DateTime? ShippedDate {get; set;}
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("Subtotal",TypeName="money")] public decimal? Subtotal {get; set;}
		}

		[Table("Summary of Sales by Year",Schema="dbo")]
		public partial class Summary_of_Sales_by_Year
		{
			[Column("ShippedDate",TypeName="datetime")] public DateTime? ShippedDate {get; set;}
			[Column("OrderID",TypeName="int")] public int OrderID {get; set;}
			[Column("Subtotal",TypeName="money")] public decimal? Subtotal {get; set;}
		}

		[Table("Suppliers",Schema="dbo")]
		public partial class Suppliers
		{
			[Column("SupplierID",TypeName="int")] public int SupplierID {get; set;}
			[Column("CompanyName",TypeName="nvarchar")] public string CompanyName {get; set;}
			[Column("ContactName",TypeName="nvarchar")] public string ContactName {get; set;}
			[Column("ContactTitle",TypeName="nvarchar")] public string ContactTitle {get; set;}
			[Column("Address",TypeName="nvarchar")] public string Address {get; set;}
			[Column("City",TypeName="nvarchar")] public string City {get; set;}
			[Column("Region",TypeName="nvarchar")] public string Region {get; set;}
			[Column("PostalCode",TypeName="nvarchar")] public string PostalCode {get; set;}
			[Column("Country",TypeName="nvarchar")] public string Country {get; set;}
			[Column("Phone",TypeName="nvarchar")] public string Phone {get; set;}
			[Column("Fax",TypeName="nvarchar")] public string Fax {get; set;}
			[Column("HomePage",TypeName="ntext")] public string HomePage {get; set;}
		}

		[Table("Territories",Schema="dbo")]
		public partial class Territories
		{
			[Column("TerritoryID",TypeName="nvarchar")] public string TerritoryID {get; set;}
			[Column("TerritoryDescription",TypeName="nchar")] public string TerritoryDescription {get; set;}
			[Column("RegionID",TypeName="int")] public int RegionID {get; set;}
		}

	}

	public abstract class TestDatabaseProcedures
	{
		[Procedure("CustOrderHist", "dbo")] public abstract void CustOrderHist([Parameter("CustomerID", "nchar", ParameterDirection.Input)] string @CustomerID);
		[Procedure("CustOrdersDetail", "dbo")] public abstract void CustOrdersDetail([Parameter("OrderID", "int", ParameterDirection.Input)] int? @OrderID);
		[Procedure("CustOrdersOrders", "dbo")] public abstract void CustOrdersOrders([Parameter("CustomerID", "nchar", ParameterDirection.Input)] string @CustomerID);
		[Procedure("Employee Sales by Country", "dbo")] public abstract void Employee_Sales_by_Country([Parameter("Beginning_Date", "datetime", ParameterDirection.Input)] DateTime? @Beginning_Date, [Parameter("Ending_Date", "datetime", ParameterDirection.Input)] DateTime? @Ending_Date);
		[Procedure("MyProcedure", "dbo")] public abstract void MyProcedure([Parameter("param1", "int", ParameterDirection.Input)] int? @param1, [Parameter("outParam", "int", ParameterDirection.InputOutput)] int? @outParam);
		[Procedure("Sales by Year", "dbo")] public abstract void Sales_by_Year([Parameter("Beginning_Date", "datetime", ParameterDirection.Input)] DateTime? @Beginning_Date, [Parameter("Ending_Date", "datetime", ParameterDirection.Input)] DateTime? @Ending_Date);
		[Procedure("SalesByCategory", "dbo")] public abstract void SalesByCategory([Parameter("CategoryName", "nvarchar", ParameterDirection.Input)] string @CategoryName, [Parameter("OrdYear", "nvarchar", ParameterDirection.Input)] string @OrdYear);
		[Procedure("Ten Most Expensive Products", "dbo")] public abstract void Ten_Most_Expensive_Products();
	}
}