//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectSql.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiTypeTable
    {
        public int Id { get; set; }
        public Nullable<long> BigInt { get; set; }
        public Nullable<bool> Bit { get; set; }
        public byte[] Binary { get; set; }
        public string Char { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> DateTime2 { get; set; }
        public Nullable<System.DateTimeOffset> DateTimeOffcet { get; set; }
        public Nullable<decimal> Decimal { get; set; }
        public Nullable<double> Float { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Int { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string NChar { get; set; }
        public string NText { get; set; }
        public Nullable<decimal> Numeric { get; set; }
        public string NVarchar { get; set; }
        public Nullable<float> Real { get; set; }
        public Nullable<System.DateTime> SmallDateTime { get; set; }
        public Nullable<short> SmallInt { get; set; }
        public Nullable<decimal> SmallMoney { get; set; }
        public string Text { get; set; }
        public Nullable<byte> TinyInt { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public byte[] Varbinary { get; set; }
        public string Varchar { get; set; }
        public string Xml { get; set; }
    }
}
